version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/letsencrypt
      - ./certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ulgen_website
    networks:
      - app-network

  ulgen_website:
    image: kaanturkmen/ulgen-website
    container_name: ulgen_website
    environment:
      REACT_APP_RESET_PASSWORD_URL: "*************"
      REACT_APP_VERIFY_EMAIL_URL: "*************"
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge